# Configura o perfil ativo na aplica��o
spring.profiles.active = prod

#Configura a abertura de sess�o no JPA
spring.jpa.open-in-view = true

spring.mvc.view.prefix: /templates/
spring.mvc.view.suffix: .html